### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by kia1349** [alisalehi1380/laravel-lang-files-translator#8]
hi my bro
good job
when i use command  php artisan translate:lang en fa i get these error

start translation. please wait...

The speed of translation of files depends on the speed of the Internet,
the number of file lines and the indentation of each key.
So please be patient until the translation of the files is finished.
Thankful

   Stichoza\GoogleTranslate\Exceptions\TranslationRequestException

  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://translate.google.com/translate_a/single?client=gtx&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=fa&q=These+credentials+do+not+match+our+records.&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=374624.230430

  at vendor\stichoza\google-translate-php\src\GoogleTranslate.php:429
    425▕         } catch (GuzzleException $e) {
    426▕             match ($e->getCode()) {
    427▕                 429, 503 => throw new RateLimitException($e->getMessage(), $e->getCode()),
    428▕                 413 => throw new LargeTextException($e->getMessage(), $e->getCode()),
  ➜ 429▕                 default => throw new TranslationRequestException($e->getMessage(), $e->getCode()),
    430▕             };
    431▕         } catch (Throwable $e) {
    432▕             throw new TranslationRequestException($e->getMessage(), $e->getCode());
    433▕         }

  1   vendor\stichoza\google-translate-php\src\GoogleTranslate.php:262
      Stichoza\GoogleTranslate\GoogleTranslate::getResponse("These credentials do not match our records.")

  2   vendor\alisalehi\laravel-lang-files-translator\src\Services\TranslateService.php:99
      Stichoza\GoogleTranslate\GoogleTranslate::translate("These credentials do not match our records.")

i see https://curl.haxx.se/libcurl/c/libcurl-errors.html
here is error detail:

CURLE_PEER_FAILED_VERIFICATION (60)

The remote server's SSL certificate or SSH fingerprint was deemed not OK. This error code has been unified with CURLE_SSL_CACERT since 7.62.0. Its previous value was 51.

**Comment by kia1349** [comment]
hi ali
i resolve problem
i must create a cert and then must put in php.ini and restart php

thanks aloat

**Comment by alisalehi1380** [comment]
Hello dear @kia1349

I found this issue and guess this is the solution.
https://github.com/Stichoza/google-translate-php/issues/91
Referred to this YouTube video => https://www.youtube.com/watch?v=f5jQqWvw44U

If you solve the problem, please keep me posted. 🙏
